version: "3"
services:
    app:
        container_name: app-react
        restart: always
        build: .
        ports: 
            - '3000:3000'

    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27016'

